### ISSUE TITLE
unregistered Jar2Exe and it has expired 

### ISSUE THREAD

**Issue by yangyl568** [WebboHsu/HotDetector#1]
windows 下载安装后报错信息如下：  请教如何解决？

Error
---------------------------
This program is generated by unregistered Jar2Exe and it has expired to run for DEMO use.

**Comment by WebboHsu** [comment]
你好！
不好意思，刚刚看到这个issue。我release的安装包使用第三方软件Jar2Exe封装，在未付费情况下，它所封装的安装包应是有一定的有效期，有效期过后不能正常使用。
我封装这个安装包时未注意到此事，向您表示歉意。

**Comment by WebboHsu** [comment]
> windows 下载安装后报错信息如下： 请教如何解决？
> 
> ## Error
> This program is generated by unregistered Jar2Exe and it has expired to run for DEMO use.

你好！
不好意思，刚刚看到这个issue。我release的安装包使用第三方软件Jar2Exe封装，在未付费情况下，它所封装的安装包应是有一定的有效期，有效期过后不能正常使用。
我封装这个安装包时未注意到此事，向您表示歉意。
